### ISSUE TITLE
Collapse similar newsfeed entries

### ISSUE THREAD

**Issue by relrod** [fedora-infra/mobile#31]
This is probably way down the road (and we may be able to do something in Datagrepper itself to make this easier somehow? Maybe @ralphbean has some ideas? :P), but it would be nice if we could collapse similar entries.

Something like...

Instead of:

```
| Some newsfeed story here
| Another here
| codeblock did X on the el6 branch
| codeblock did X on the fedora18 branch
| codeblock did X on the fedora19 branch
| codeblock did X on the fedora20 branch
| X was tagged into trashcan by oscar
| X was tagged into trashcan by oscar
| X was tagged into trashcan by oscar
| X was tagged into trashcan by oscar
```

Have:

```
| Some newsfeed story here
| Another here
| codeblock did 4 things to X. Tap to expand.
| oscar tagged 5 things into trashcan. Tap to expand.
```

I think this would make the newsfeed easier to comprehend and more useful.

**Comment by relrod** [comment]
Maybe we could somehow offer an endpoint in datagrepper where similar stories are sent as a list object or something? I'm not sure how intelligent we could have to make it. i.e., what constitutes a "similar story"?

@ralphbean is this worth filing a bug on in the datagrepper repo? Or something I should just try to do in Mobile at some point way down the road on my own?

**Comment by ralphbean** [comment]
> Maybe we could somehow offer an endpoint in datagrepper where similar stories are sent as a list object or something? I'm not sure how intelligent we could have to make it. i.e., what constitutes a "similar story"?

Good idea.

> @ralphbean is this worth filing a bug on in the datagrepper repo? Or something I should just try to do in Mobile at some point way down the road on my own?

Yeah, let's do it in datagrepper.  We have `/raw`, `/id`.. maybe we add a `/summary`?

**Comment by relrod** [comment]
Closing this, track in fedora-infra/datagrepper#132.
