### ISSUE TITLE
Have a downloadable APK always at master's HEAD.

### ISSUE THREAD

**Issue by relrod** [fedora-infra/mobile#4]
It would be nice if we could have a download of the latest APK (from HEAD of the git repo's master branch) always available.

Some ways to solve this:
- Look into whether or not this is something Jenkins can do. Is it possible to have it save the apk file of a build somewhere web-accessible?
- Otherwise, we can write a really really simple Flask script that will receive the GitHub POST hook, perform a build, and move it somewhere. A persistent cloud instance would work fine for this.

I'm thinking option 2 is the way to go here, and currently waiting to find out why creating a persistent cloud instance isn't working.

**Comment by relrod** [comment]
This is roughly done. Short URL to HEAD is http://da.gd/j - Closing this ticket.

The only thing I don't like is that you have to log in (via openid) to download the .apk, rather than it being public.

@puiterwijk is that fixable if we want Jenkins to host them, or would that require it uploading the result to somewhere else?

**Comment by puiterwijk** [comment]
The permissions have now been updated to allow anonymous download of the APK.

**Comment by relrod** [comment]
Thanks! :tada:
